# Generated by Django 5.0.14 on 2026-08-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_sharedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='model',
            field=models.CharField(choices=[('sonnet', 'Sonnet'), ('opus', 'Opus')], default='sonnet', max_length=16),
        ),
    ]
