# Generated by Django 5.0.14 on 2026-08-22

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='total_cost_usd',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10),
        ),
    ]
